name: Nullstone
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Nullstone
        uses: nullstone-io/setup-nullstone-action@v0

      - name: Find version
        id: version
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}

      - id: publish
        name: Publish
        run: |
          nullstone modules publish --version=${{ steps.version.outputs.tag }}
